#!/bin/bash

author_name=${GIT_AUTHOR_NAME}
if [[ -z "$author_name" ]]; then
  author_name=$(git config user.name)
fi

author_email=${GIT_AUTHOR_EMAIL}
if [[ -z "$author_email" ]]; then
  author_email=$(git config user.email)
fi

if [[ "$author_name" == "Square" || "$author_email" == "github@squareup.com" ]]; then
  echo "Error: You must commit as a user other than '$author_name <$author_email>'."
  echo
  echo "Use a tool such as \`hitch' or \`git-pair' to set your"
  echo "git commit author name and email as you and your pair(s) name:"
  echo
  echo "  $ hitch adam jane  # OR git pair aw js"
  echo "  Adam West and Jane Smith <github+adam+jane@squareup.com>"
  exit 1
fi
